# -*- coding: utf-8 -*-
"""bert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q9I5ke-XLLh5NTOpVnY0ZHw2iJ0tawTZ
"""

"""#Reddit BERT 분석"""

import pandas as pd
reddit = pd.read_csv('dsm_data.csv')

from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('paraphrase-distilroberta-base-v1')

word_list = reddit["text"].to_list()

embeddings = model.encode(word_list, convert_to_tensor=True)
cosine_scores = util.pytorch_cos_sim(embeddings, embeddings)

org = 500
temp = cosine_scores[org]
temp.argsort(descending=False)[0:10]

for i in temp.argsort(descending=False)[0:10]:
    print(f"{i}. {word_list[org]} <> {word_list[i]} \nScore: {cosine_scores[org][i]:.4f}")

org = 500
temp = cosine_scores[org]
temp.argsort(descending=True)[0:10]

for i in temp.argsort(descending=True)[0:10]:
    print(f"{i}. {word_list[org]} <> {word_list[i]} \nScore: {cosine_scores[org][i]:.4f}")
